### ISSUE TITLE
Samples do not function for multiple reasons

### ISSUE THREAD

**Issue by stewartadam** [Azure/azure-docs-sdk-java#410]
1. Version is required on Maven `<dependency>` snippets
2. @EnableOAuth2Sso is missing (now requires new Maven dependency):
    ```<dependency>
    			<groupId>org.springframework.security.oauth.boot</groupId>
    			<artifactId>spring-security-oauth2-autoconfigure</artifactId>
    			<version>2.0.0.RELEASE</version>
    		</dependency>
    ```
3. Attempting to access a protected URL results in exception `org.springframework.security.oauth2.client.resource.UserRedirectRequiredException: A redirect is required to get the users approval`

    Debugging info:
    ```
    ...
    2018-04-03 12:16:05.274  INFO 41754 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Creating filter chain: org.springframework.security.web.util.matcher.AnyRequestMatcher@1, [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@1706a5c9, org.springframework.security.web.context.SecurityContextPersistenceFilter@31da3d60, org.springframework.security.web.header.HeaderWriterFilter@468be356, org.springframework.security.web.csrf.CsrfFilter@6a0cbc6f, org.springframework.security.web.authentication.logout.LogoutFilter@4b869331, org.springframework.security.oauth2.client.filter.OAuth2ClientAuthenticationProcessingFilter@64412d34, com.microsoft.azure.spring.autoconfigure.aad.AADAuthenticationFilter@221ca7c, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@65ec8b24, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@5e8c34a0, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@4d178d55, org.springframework.security.web.session.SessionManagementFilter@4df39a88, org.springframework.security.web.access.ExceptionTranslationFilter@58e85c6f, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@35178483]
    ...
    org.springframework.security.oauth2.client.resource.UserRedirectRequiredException: A redirect is required to get the users approval
    	at org.springframework.security.oauth2.client.token.grant.code.AuthorizationCodeAccessTokenProvider.getRedirectForAuthorization(AuthorizationCodeAccessTokenProvider.java:359) ~[spring-security-oauth2-2.2.1.RELEASE.jar:na]
    	at org.springframework.security.oauth2.client.token.grant.code.AuthorizationCodeAccessTokenProvider.obtainAccessToken(AuthorizationCodeAccessTokenProvider.java:205) ~[spring-security-oauth2-2.2.1.RELEASE.jar:na]
    	at org.springframework.security.oauth2.client.OAuth2RestTemplate.acquireAccessToken(OAuth2RestTemplate.java:221) ~[spring-security-oauth2-2.2.1.RELEASE.jar:na]
    	at org.springframework.security.oauth2.client.OAuth2RestTemplate.getAccessToken(OAuth2RestTemplate.java:173) ~[spring-security-oauth2-2.2.1.RELEASE.jar:na]
    	at org.springframework.security.oauth2.client.filter.OAuth2ClientAuthenticationProcessingFilter.attemptAuthentication(OAuth2ClientAuthenticationProcessingFilter.java:105) ~[spring-security-oauth2-2.2.1.RELEASE.jar:na]
    	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212) ~[spring-security-web-5.0.3.RELEASE.jar:5.0.3.RELEASE]
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.3.RELEASE.jar:5.0.3.RELEASE]
    	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) ~[spring-security-web-5.0.3.RELEASE.jar:5.0.3.RELEASE]
    ...
    ```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cf5423d-6c4c-26a8-89bb-7686794716d0
* Version Independent ID: 734cd358-3dfb-14cd-ee3d-5ce54be8d613
* Content: [How to use the Spring Boot Starter for Azure Active Directory](https://docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory)
* Content Source: [docs-ref-conceptual/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md](https://github.com/Azure/azure-docs-sdk-java/blob/live/docs-ref-conceptual/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md)
* Service: **active-directory**
* GitHub Login: @rmcmurray
* Microsoft Alias: **robmcm**

**Comment by bill-blackmon** [comment]
This example is broken. Please see item #3 and post solution. stewartadams hints, while useful,  do not solve the problem.  Nor do the 'See also:' items above. These issues have been opened for an entire month with no resolution. You need to keep up!

**Comment by tschn** [comment]
any idea on when this example will be fixed?

**Comment by rmcmurray** [comment]
@tschn - we are working on that article now; we should have an update soon.

**Comment by stewartadam** [comment]
FWIW, if you're looking for something that works with Spring 5, I published my own sample here:
https://github.com/stewartadam/azuread-springsecurity5-oauth2-kickstart

It uses the built-in OAuth 2 support for Spring Security for Spring 5 instead of the add-in module, which is no longer compatible with Spring 5.

**Comment by jason279** [comment]
@brunoborges any updating for the issue? Still get the "A redirect is required to get the users approval" exception. Is there anyone can help to fix it?
Thanks!!

**Comment by rmcmurray** [comment]
@jason279 - I am experiencing the same issue that you are seeing, and we are currently looking into that.

However, for now you can use the example [azure-active-directory-spring-boot-sample](https://github.com/Microsoft/azure-spring-boot/tree/master/azure-spring-boot-samples/azure-active-directory-spring-boot-sample) application as a starting point for building an application; that sample has been tested and it works as expected.

**Comment by jason279** [comment]
OK. Thanks @rmcmurray .

**Comment by rmcmurray** [comment]
@stewartadam, @jason279, and @tschn - we've made changes the the Spring starter which resolve the issues that you were seeing, and we've updated the article accordingly:

https://docs.microsoft.com/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory

Thanks!

**Comment by GauravWable** [comment]
Error in import (HelloController.java):
The import org.springframework.security.access.prepost.PreAuthorize cannot be resolved

And
(WebSecurityConfig.java)
The type org.springframework.security.authentication.AuthenticationManager cannot be resolved. It is indirectly referenced from required .class files

These files are present under 
Maven Dependencies > spring-security-core-5.0.6.RELEASE.jar

Please help to resolve these errors. Thanks.
